src/Urjavac/RepoBundle/Entity/Recurso.php
<?php

namespace Urjavac\RepoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Recurso
 *
 * @ORM\Table(name="repo_recurso", indexes={@ORM\Index(name="IDX_B2BB3764FD61E233", columns={"idusuario"}), @ORM\Index(name="IDX_B2BB376410B7C824", columns={"idAsignatura"})})
 * @ORM\Entity(repositoryClass="Urjavac\RepoBundle\Entity\RecursoRepository")
 */
class Recurso {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=100, nullable=false)
     */
    protected $nombre;

    /**
     * @var string
     *
     * @ORM\Column(name="descripcion", type="string", length=1000, nullable=false)
     */
    protected $descripcion;

    /**
     * @var string
     *
     * @ORM\Column(name="enlace", type="string", length=1000, nullable=true)
     */
    protected $enlace;

    /**
     * @var boolean
     *
     * @ORM\Column(name="oficial", type="boolean", nullable=false)
     */
    protected $oficial;

    /**
     * @var boolean
     *
     * @ORM\Column(name="revisado", type="boolean", nullable=false)
     */
    protected $revisado;

    /**
     * @var integer
     *
     * @ORM\Column(name="valor_positivo", type="integer", nullable=true)
     */
    protected $valor_positivo;

    /**
     * @var integer
     *
     * @ORM\Column(name="valor_negativo", type="integer", nullable=true)
     */
    protected $valor_negativo;

    /**
     * @var \Urjavac\RepoBundle\Entity\Curso
     *
     * @ORM\ManyToOne(targetEntity="Urjavac\RepoBundle\Entity\Curso")
     * @ORM\JoinColumn(name="curso", referencedColumnName="id")
     */
    protected $curso;

    /**
     *
     * @ORM\ManyToMany(targetEntity="Usuario", inversedBy="votadoPositivo")
     * @ORM\JoinTable(name="votos_positivos_recurso")
     */
    protected $votosPositivosDe;

    /**
     * @ORM\ManyToMany(targetEntity="Usuario", inversedBy="votadoNegativo")
     * @ORM\JoinTable(name="votos_negativos_recurso")
     */
    protected $votosNegativosDe;

    /**
     * @var \Urjavac\RepoBundle\Entity\Asignatura
     *
     * @ORM\ManyToOne(targetEntity="Urjavac\RepoBundle\Entity\Asignatura")
     * @ORM\JoinColumn(name="idasignatura", referencedColumnName="id")
     */
    protected $idasignatura;

    /**
     * @var \Urjavac\RepoBundle\Entity\Usuario
     *
     * @ORM\ManyToOne(targetEntity="Urjavac\RepoBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="idusuario", referencedColumnName="id")
     */
    protected $idusuario;

    /**
     * @var \Urjavac\RepoBundle\Entity\Tiporecurso
     *
     * @ORM\ManyToOne(targetEntity="Urjavac\RepoBundle\Entity\Tiporecurso")
     * @ORM\JoinColumn(name="tipo", referencedColumnName="id")
     */
    protected $tipo;

    /**
     * @var \Urjavac\RepoBundle\Entity\Formato
     *
     * @ORM\ManyToOne(targetEntity="Urjavac\RepoBundle\Entity\Formato")
     * @ORM\JoinColumn(name="formato", referencedColumnName="id")
     */
    protected $formato;

    /**
     * @var UploadedFile
     * @Assert\File(maxSize="20M")
     */
    protected $file;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Recurso
     */
    public function setNombre($nombre) {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string
     */
    public function getNombre() {
        return $this->nombre;
    }

    /**
     * Set descripcion
     *
     * @param string $descripcion
     * @return Recurso
     */
    public function setDescripcion($descripcion) {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get descripcion
     *
     * @return string
     */
    public function getDescripcion() {
        return $this->descripcion;
    }

    /**
     * Set enlace
     *
     * @param string $enlace
     * @return Recurso
     */
    public function setEnlace($enlace) {
        $this->enlace = $enlace;

        return $this;
    }

    /**
     * Get enlace
     *
     * @return string
     */
    public function getEnlace() {
        return $this->enlace;
    }

    /**
     * Set oficial
     *
     * @param boolean $oficial
     * @return Recurso
     */
    public function setOficial($oficial) {
        $this->oficial = $oficial;

        return $this;
    }

    /**
     * Get oficial
     *
     * @return boolean
     */
    public function getOficial() {
        return $this->oficial;
    }

    /**
     * Set revisado
     *
     * @param boolean $revisado
     * @return Recurso
     */
    public function setRevisado($revisado) {
        $this->revisado = $revisado;

        return $this;
    }

    /**
     * Get revisado
     *
     * @return boolean
     */
    public function getRevisado() {
        return $this->revisado;
    }

    /**
     * Set curso
     *
     * @param \Urjavac\RepoBundle\Entity\Curso $curso
     * @return Recurso
     */
    public function setCurso(\Urjavac\RepoBundle\Entity\Curso $curso = null) {
        $this->curso = $curso;

        return $this;
    }

    /**
     * Get curso
     *
     * @return \Urjavac\RepoBundle\Entity\Curso
     */
    public function getCurso() {
        return $this->curso;
    }

    /**
     * Set idasignatura
     *
     * @param \Urjavac\RepoBundle\Entity\Asignatura $idasignatura
     * @return Recurso
     */
    public function setIdasignatura(\Urjavac\RepoBundle\Entity\Asignatura $idasignatura = null) {
        $this->idasignatura = $idasignatura;

        return $this;
    }

    /**
     * Get idasignatura
     *
     * @return \Urjavac\RepoBundle\Entity\Asignatura
     */
    public function getIdasignatura() {
        return $this->idasignatura;
    }

    /**
     * Set idusuario
     *
     * @param \Urjavac\RepoBundle\Entity\Usuario $idusuario
     * @return Recurso
     */
    public function setIdusuario(\Urjavac\RepoBundle\Entity\Usuario $idusuario = null) {
        $this->idusuario = $idusuario;

        return $this;
    }

    /**
     * Get idusuario
     *
     * @return \Urjavac\RepoBundle\Entity\Usuario
     */
    public function getIdusuario() {
        return $this->idusuario;
    }

    /**
     * Set tipo
     *
     * @param \Urjavac\RepoBundle\Entity\Tiporecurso $tipo
     * @return Recurso
     */
    public function setTipo(\Urjavac\RepoBundle\Entity\Tiporecurso $tipo = null) {
        $this->tipo = $tipo;

        return $this;
    }

    /**
     * Get tipo
     *
     * @return \Urjavac\RepoBundle\Entity\Tiporecurso
     */
    public function getTipo() {
        return $this->tipo;
    }

    /**
     * Set formato
     *
     * @param \Urjavac\RepoBundle\Entity\Formato $formato
     * @return Recurso
     */
    public function setFormato(\Urjavac\RepoBundle\Entity\Formato $formato = null) {
        $this->formato = $formato;

        return $this;
    }

    /**
     * Get formato
     *
     * @return \Urjavac\RepoBundle\Entity\Formato
     */
    public function getFormato() {
        return $this->formato;
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null) {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile() {
        return $this->file;
    }

    public function getAbsolutePath() {
        return null === $this->enlace ? null : $this->getUploadRootDir() . '/' . $this->enlace;
    }

    public function getWebPath() {
        return null === $this->enlace ? null : '/' . $this->getUploadDir() . '/' . $this->enlace;
    }

    public function getAdminPath() {
        return null === $this->enlace ? null : '/web/' . $this->getUploadDir() . '/' . $this->enlace;
    }

    protected function getUploadRootDir() {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    protected function getUploadDir() {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/recursos';
    }

    public function upload() {
        // the file property can be empty if the field is not required
        if (null === $this->getFile()) {
            return;
        }

        // aquí usa el nombre de archivo original pero lo debes
        // sanear al menos para evitar cualquier problema de seguridad
        // move takes the target directory and then the
        // target filename to move to
        $extension = $this->file->guessExtension();
        if (!$extension) {
            // no se puede deducir la extensión
            $extension = 'bin';
        }
        $nombre = (rand(1, 99999) . '.' . $extension);

        $this->getFile()->move($this->getUploadRootDir(), $nombre);

        // set the path property to the filename where you've saved the file
        $this->enlace = $nombre;

        // limpia la propiedad «file» ya que no la necesitas más
        $this->file = null;
    }

    public function removeUpload() {
        $file = $this->getAbsolutePath();
        if (is_file($file)) {
            $unlink = unlink($file);
            if ($unlink) {
                $this->file = null;
            }
        }
    }

    /**
     * Set valor_positivo
     *
     * @param integer $valorPositivo
     * @return Recurso
     */
    public function setValorPositivo($valorPositivo) {
        $this->valor_positivo = $valorPositivo;

        return $this;
    }

    /**
     * Get valor_positivo
     *
     * @return integer
     */

src/Urjavac/RepoBundle/Form/RecursoType.php
<?php

namespace Urjavac\RepoBundle\Form;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class RecursoType extends AbstractType {

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {

        $builder
                ->add('idasignatura', 'entity', array('label' => 'Asignatura:', 'class' => 'UrjavacRepoBundle:Asignatura', 'query_builder' => function(EntityRepository $er) {
                return $er->createQueryBuilder('a')
                        ->orderBy('a.identificador', 'ASC');
            },))
                ->add('nombre', 'text', array('label' => 'Nombre:', 'required' => true))
                ->add('descripcion', 'textarea', array('max_length' => 140, 'required' => true, 'label' => 'Descripción:'))
                ->add('curso', 'entity', array('label' => 'Curso:', 'class' => 'UrjavacRepoBundle:Curso', 'query_builder' => function(EntityRepository $er) {
                return $er->createQueryBuilder('c')
                        ->orderBy('c.curso', 'DESC');
            },))
                ->add('tipo', 'entity', array('label' => 'Tipo:', 'class' => 'UrjavacRepoBundle:Tiporecurso'))
                ->add('formato', 'entity', array('label' => 'Formato:', 'class' => 'UrjavacRepoBundle:Formato',
                    'query_builder' => function(EntityRepository $er) {
                return $er->createQueryBuilder('f')
                        ->orderBy('f.nombre', 'ASC');
            },))
                ->add('oficial', 'checkbox', array('label' => "¿Es oficial?", 'required' => false))
                ->add('file', 'file', array('required' => true))
                ->add('reset', 'reset', array('label' => 'Reset'))
                ->add('enviar', 'submit', array('label' => 'Subir'))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'Urjavac\RepoBundle\Entity\Recurso',
            'csrf_protection' => false
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'urjavac_repobundle_recurso';
    }

}

src/Urjavac/RepoBundle/Resources/views/Recurso/detalles_recurso.html.twig
{% extends 'UrjavacRepoBundle::layout.html.twig' %}

{% block scripts %}
    <script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
{% endblock %}

{% block contenido %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Detalles del recurso</h3>
                </div>
                {% if not recurso.revisado %}
                    <div class="panel-body  text-center">
                        <span class="text-danger">Todavía no puedes descargar este recurso porque aún tenemos que revisarlo.</span>
                    </div>
                    {#                {% else %}#}
                {% endif %}
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>Nombre:</th>
                            <td>{{ recurso.nombre }}</td>
                        </tr>
                        <tr>
                            <th>Descripción:</th>
                            <td>{{ recurso.descripcion }}</td>
                        </tr>
                        <tr>
                            <th>Asignatura:</th>
                            <td>{{ recurso.idasignatura.nombre }}</td>
                        </tr>
                        <tr>
                            <th>Tipo:</th>
                            <td>{{ recurso.tipo.nombre }}</td>
                        </tr>
                        <tr>
                            <th>Formato:</th>
                            <td>{{ recurso.formato }}</td>
                        </tr>
                        <tr>
                            <th>Curso:</th>
                            <td>{{ recurso.curso }}</td>
                        </tr>
                        <tr>
                            <th>Enlace:</th>
                                {% if recurso.revisado %}
                                <td><a href="{{ recurso.webPath }}" target="_blank"><button class="btn btn-info btn-xs"><i class="fa fa-download"></i> Descargar</button></a></td>
                            {% else %}
                                <td><a href="{{ recurso.webPath }}" target="_blank"><button class="btn btn-info btn-xs" disabled="disabled"><i class="fa fa-download"></i> Descargar</button></a></td>
                            {% endif %}
                        </tr>
                        <tr>
                            <th>Oficial:</th>
                            <td>
                                {%if recurso.oficial%}
                                    Sí
                                {%else%}
                                    No
                                {%endif%}
                            </td>
                        </tr>
                        <tr>
                            <th>Uploader:</th>
                            <td>{{ recurso.idusuario.username }}</td>
                        </tr>
                    </table>
                </div>
                <div class="panel-footer">
                    <div class="">Puntuacion: {{ recurso.valorPositivo }} votos positivos / {{ recurso.valorNegativo }} votos negativos.</div>
                    <div class="">
                        {% if app.user.hasVotadoPositivo(recurso) %}
                            <a href="{{ path('recursos_quitar_voto_positivo',{'idrecurso':recurso.id}) }}" class="button-link">
                                <button class="btn btn-xs btn-success"><i class="fa fa-thumbs-o-up"></i> Quitar +1</button>
                            </a>
                        {%else%}
                            <a href="{{ path('recursos_voto_positivo',{'idrecurso':recurso.id}) }}" class="button-link">
                                <button class="btn btn-xs btn-success"><i class="fa fa-thumbs-o-up"></i> Votar +1</button>
                            </a>
                        {%endif%}
                        {% if app.user.hasVotadoNegativo(recurso) %}
                            <a href="{{ path('recursos_quitar_voto_negativo', {'idrecurso':recurso.id}) }}" class="button-link">
                                <button type="button" class="btn btn-xs btn-danger"><i class="fa fa-thumbs-o-down"></i> Quitar -1</button>
                            </a>
                        {%else%}
                            <a href="{{ path('recursos_voto_negativo', {'idrecurso':recurso.id}) }}" class="button-link">
                                <button type="button" class="btn btn-xs btn-danger"><i class="fa fa-thumbs-o-down"></i> Votar -1</button>
                            </a>
                        {%endif%}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="well">
                <h4 class="text-muted">Escribe un comentario sobre este recurso</h4>
                {{ form_start(form) }}
                <div class="form-group">
                    {{ form_label(form.mensaje) }}
                    {{ form_widget(form.mensaje,{'attr':{'class':'form-control'}, 'id':'ckeditor'}) }}
                </div>
                {{ form_widget(form.comentar,{'attr':{'class':'btn btn-info'}}) }}
                {{ form_end(form) }}
            </div>
            <hr>
        </div>
    </div>
    {%if not listaMensajes is empty%}
        {% for mensaje in listaMensajes%}
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="well">
                        <div>
                            <strong>Autor: </strong>
                            {{ mensaje.autor.username }}
                        </div>
                        <strong>Fecha y hora: </strong>{{ mensaje.fecha|date('d-m-Y H:i') }}<br>
                        <strong>Comentario:</strong><br>
                        {{mensaje.mensaje|nl2br}}
                        <br>
                        {% if mensaje.autor.id == app.user.id or is_granted('ROLE_ADMIN') %}
                            <a href="{{ path('recurso_mensaje_borrar',{'idmensaje':mensaje.id,'idrecurso':recurso.id}) }}"><i class="fa fa-trash-o"></i> Borrar</a>
                        {%endif%}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
                <div class="well">
                    <h4 class="text-muted">No hay ningún comentario todavía.</h4>
                </div>
            </div>
        </div>
    {%endif%}

{% endblock %}

src/Urjavac/RepoBundle/Resources/views/Recurso/email_nuevo_recurso_admin.html.twig
<html>
    <body>
        <h3>Nuevo recurso en la asignatura: {{ asignatura.nombre }}.</h3>
        <p>Hay un nuevo recurso disponible en la asignatura: {{ asignatura.nombre }}</p>
        Estos son los datos del nuevo recurso:
        <table>
            <tr>
                <th>Nombre:</th>
                <td>{{ recurso.nombre }}</td>
            </tr>
            <tr>
                <th>Descripción:</th>
                <td>{{ recurso.descripcion }}</td>
            </tr>
            <tr>
                <th>Asignatura:</th>
                <td>{{ recurso.idasignatura.nombre }}</td>
            </tr>
            <tr>
                <th>Oficial:</th>
                <td>{{ (recurso.oficial == 1)? "Sí":"No" }}</td>
            </tr>
            <tr>
                <th>Revisado:</th>
                <td>{{ (recurso.revisado == 1)? "Sí":"No" }}</td>
            </tr>
            <tr>
                <th>Curso:</th>
                <td>{{ recurso.curso.curso }}</td>
            </tr>
            <tr>
                <th>Tipo:</th>
                <td>{{ recurso.tipo.nombre }}</td>
            </tr>
            <tr>
                <th>Formato:</th>
                <td>{{ recurso.formato.nombre }}</td>
            </tr>
        </table>
        <p>Puedes verificar el nuevo recurso desde este enlace: <a href="{{ url('admin_recurso_lista')}}">aquí</a> </p>
        <br>
        <p>Muchas gracias por tu colaboración.</p>
        <p>Un saludo.</p>
        <p>La administración de URJavaC.</p>
    </body>
</html>

src/Urjavac/RepoBundle/Resources/views/Recurso/index.html.twig
{% extends "UrjavacRepoBundle::layout.html.twig" %}

{% block titulo %}Recursos :: Repositorio{% endblock %}

{% block breadcrumb %}
    <li>
        <a href="{{ path('recurso_ver_todos') }}">Lista de recursos</a>
    </li>
{% endblock %}

{% block contenido %}
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-info">

                <div class="panel-heading">
                    <p class="panel-title" >
                        <span class="glyphicon glyphicon-search"></span> Filtros
                    </p>
                </div>
                <div class="panel-body">
                    {{form_start(form)}}
                    {% for radio in form.radios %}
                        <div class="radio-button">
                            {{ form_widget(radio) }}
                            {{ form_label(radio) }}
                        </div>
                    {%endfor%}
                    <br>
                    <div class="form-group">
                        {{ form_label(form.asignatura) }}
                        {{ form_widget(form.asignatura, {'attr':{'class':'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label(form.tipo) }}
                        {{ form_widget(form.tipo, {'attr':{'class':'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label(form.curso) }}
                        {{ form_widget(form.curso, {'attr':{'class':'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label(form.formato) }}
                        {{ form_widget(form.formato, {'attr':{'class':'form-control'}}) }}
                    </div>
                    <button type="submit" class="btn btn-info btn-sm center-block"><i class="fa fa-search"></i> Filtrar</button>
                    {{form_end(form)}}
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-9">
            {% if recursos is empty %}
                <div class="well">
                    <h4 class="text-muted text-center">No hay ningún recurso con estos criterios de búsqueda o en la base de datos.</h4>
                </div>
            {% else %}
                {% for recurso in recursos%}
                    <div class="well well-recurso">
                        <div class="row">
                            <div class="col-xs-1 col-sm-1 hidden-xs">
                                <div class="icon-recurso">
                                    <a href="{{ path('recurso_detalles',{'idrecurso':recurso.id}) }}"><i class="{{recurso.formato.icono}} text-muted"></i></a>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-11">
                                <ul class="info-recurso">
                                    <li>
                                        <a href="{{ path('recurso_detalles',{'idrecurso':recurso.id}) }}">
                                            <h4 class="nombre-recurso">{{recurso.nombre}}</h4>
                                        </a>
                                        {%if recurso.oficial%}
                                            <label class="label label-success"><i class="fa fa-university"></i> Oficial</label>
                                        {% else %}
                                            <label class="label label-warning"><i class="fa fa-users"></i> No oficial</label>
                                        {%endif%}
                                        {% if recurso.revisado %}
                                            <label class="label label-success"><i class="fa fa-check"></i> Revisado</label>
                                        {% else %}
                                            <label class="label label-warning"><i class="fa fa-times"></i> No revisado</label>
                                        {% endif %}
                                    </li>
                                    <li>
                                        <p class="descripcion-recurso">{{recurso.descripcion}}</p>
                                    </li>
                                    <li>
                                        <div class="asignatura-recurso">
                                            <strong>Asignatura:</strong>
                                            {{recurso.idasignatura.nombre}}
                                        </div>
                                    </li>
                                    <li>
                                        <div class="curso-recurso">
                                            <strong>Curso:</strong>
                                            {{recurso.curso.curso}}
                                        </div>
                                    </li>
                                    <li>
                                        <div class="tipo-recurso">
                                            <strong>Tipo:</strong>
                                            {{recurso.tipo.nombre}}
                                        </div>
                                    </li>
                                    <li>
                                        <div class=""><strong>Puntuacion:</strong> {{ recurso.valorPositivo }} votos positivos / {{ recurso.valorNegativo }} votos negativos.</div>
                                    </li>
                                    <li>
                                        <a style="text-decoration: none;" href="{{ path('recurso_detalles',{'idrecurso':recurso.id}) }}">
                                            <button class="btn btn-primary btn-xs"><i class="fa fa-info"></i> Ver detalles</button>
                                        </a>
                                        {% if not recurso.revisado %}
                                            <button class="btn btn-info btn-xs" disabled="disabled"><i class="fa fa-download"></i> Descargar</button>
                                        {% else %}
                                            <a style="text-decoration: none;" href="{{ recurso.webPath }}" target="blank">
                                                <button class="btn btn-info btn-xs"><i class="fa fa-download"></i> Descargar</button>
                                            </a>
                                        {% endif %}
                                        {% if app.user.hasVotadoPositivo(recurso) %}
                                            <a href="{{ path('recursos_quitar_voto_positivo',{'idrecurso':recurso.id}) }}" class="button-link">
                                                <button class="btn btn-xs btn-success"><i class="fa fa-thumbs-o-up"></i> Quitar +1</button>
                                            </a>
                                        {%else%}
                                            <a href="{{ path('recursos_voto_positivo',{'idrecurso':recurso.id}) }}" class="button-link">
                                                <button class="btn btn-xs btn-success"><i class="fa fa-thumbs-o-up"></i> Votar +1</button>
                                            </a>
                                        {%endif%}
                                        {% if app.user.hasVotadoNegativo(recurso) %}
                                            <a href="{{ path('recursos_quitar_voto_negativo', {'idrecurso':recurso.id}) }}" class="button-link">
                                                <button type="button" class="btn btn-xs btn-danger"><i class="fa fa-thumbs-o-down"></i> Quitar -1</button>
                                            </a>
                                        {%else%}
                                            <a href="{{ path('recursos_voto_negativo', {'idrecurso':recurso.id}) }}" class="button-link">
                                                <button type="button" class="btn btn-xs btn-danger"><i class="fa fa-thumbs-o-down"></i> Votar -1</button>
                                            </a>
                                        {%endif%}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {%endfor%}
            {%endif%}
        </div>
    </div>
{% endblock %}